name: Deploy to staging
on: 
  push:
    branches:
      - "main"

jobs: 
  redeploy_everything:
    name: Deploying everything to staging
    
    steps:
      -name: SSH into the server
      -run: |
          echo ${{secrets.AWS_KEYPAIR}} &> ~/ssh_key
          ssh -i ~/ssh_key root@172.31.32.47
          cd bms && git pull
          pnpm install
          pnpm run build
          pm2 restart fe-server
          pm2 restart http-server
          pm2 restart ws-server
          
